insert into packs values('0','0','第１弾');
insert into packs values('1','0','第２弾');
insert into packs values('2','0','第３弾');
insert into packs values('3','0','第４弾');
insert into packs values('4','0','第５弾');
insert into packs values('5','1','第１弾');
insert into packs values('6','1','第２弾');
insert into packs values('7','1','第３弾');
insert into packs values('8','1','第４弾');
insert into packs values('9','2','第１弾');
insert into packs values('10','2','第２弾');
insert into packs values('11','2','第３弾');
insert into packs values('12','2','第４弾');
insert into packs values('13','3','第１弾');
insert into packs values('14','3','第２弾');
insert into packs values('15','3','第３弾');
insert into packs values('16','3','第４弾');
insert into packs values('18','4','第１弾');
insert into packs values('19','4','第２弾');
insert into packs values('20','4','第３弾');
insert into packs values('21','4','第４弾');
insert into packs values('22','4','第５弾');
insert into packs values('23','5','第１弾');
insert into packs values('24','5','第２弾');
insert into packs values('25','5','第３弾');
insert into packs values('26','5','第４弾');
insert into packs values('27','6','第１弾');
insert into packs values('28','6','第２弾');
insert into packs values('29','6','第３弾');
insert into packs values('30','6','第４弾');
insert into packs values('31','7','第１弾');
insert into packs values('35','7','第２弾');
insert into packs values('38','7','第３弾');
insert into packs values('36','7','第４弾');
insert into packs values('45','8','第１弾');
insert into packs values('46','8','第２弾');
insert into packs values('47','8','第３弾');
insert into packs values('48','8','第４弾');
insert into packs values('42','9','ファースト・コンタクト');
insert into packs values('43','9','ダークサイド');
insert into packs values('44','9','ガイアール・ビクトリー');
insert into packs values('49','9','ライジング・ホープ');
insert into packs values('41','10','大決戦オールスター１２');
insert into packs values('37','10','ゴールデン・エイジ');
insert into packs values('39','10','ビクトリー・ラッシュ');
insert into packs values('40','10','ゴールデン・ドラゴン');
insert into packs values('34','10','グレイト・ミラクル');
insert into packs values('33','10','ブラック・ボックス・パック');
insert into packs values('32','10','ホワイト・ゼニス・パック');
insert into packs values('51','11','双龍パック');
insert into packs values('17','11','ベストチャレンジャー');
insert into packs values('52','11','コロコロドリーム');
insert into packs values('53','11','コロコロドリーム2');
insert into packs values('54','11','コロコロドリーム3');
insert into packs values('57','11','ヒーローズクロス');
insert into packs values('61','12','エントリーパック・ゼロ　パーフェクト・エンジェル');
insert into packs values('60','12','ライジング・ダッシュデッキ　反撃ブロック！');
insert into packs values('59','12','変形デッキセット　DX鬼エンジェル');
insert into packs values('58','12','変形デッキセット　DX鬼ドラゴン');
insert into packs values('62','12','1stデッキ　アウトレイジ・ダッシュ');
insert into packs values('63','12','1stデッキ　オラクル・ダッシュ');
insert into packs values('64','12','ルナティック・ゴッド');
insert into packs values('65','12','ウルトラ・NEX');
insert into packs values('66','12','マッド・ロック・チェスター');
insert into packs values('67','12','ザ・ゴッド・キングダム');
insert into packs values('55','13','スーパーデッキ ゼロ');
insert into packs values('56','13','スーパーデッキ クロス');
insert into packs values(null,'98','プロモ');
insert into packs values(null,'99','全種');
