-- =====================================================================
-- 20260924_assign_neo_evolution.sql の事前確認 (読み取りのみ・何度実行してもよい)
-- =====================================================================

SET NAMES utf8;

-- 実行済みかどうか (1 行出たら実行済み。パッチ本体は流さない)
SHOW TABLES LIKE 'cards_bak_20260924_neo_evo';

-- パッチ1が先に実行されているか (14/15 が残っていたら先にパッチ1を流す。0 件であること)
SELECT COUNT(*) AS legacy_14_15
FROM cards
WHERE TRIM(IFNULL(evolution, '')) IN ('14', '15');

-- G-NEO進化の件数 (目安: 57 件)
SELECT COUNT(*) AS gneo_cards
FROM cards
WHERE
  str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'G-', 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'G-', 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'G-', 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'G-', 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'G-', 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
;

-- NEO進化の件数 (目安: 259 件)
SELECT COUNT(*) AS neo_cards
FROM cards
WHERE
  str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'NEO進化', ':', '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
  OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'NEO進化', ':', '%')
;

-- 対象のうち、既に進化コードが入っているカード (目安: 7 件・すべて 8=マナ進化)
SELECT id, name, evolution, LEFT(str, 60) AS str_head
FROM cards
WHERE TRIM(IFNULL(evolution, '')) <> ''
  AND (
    str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
  )
ORDER BY id;

-- マーカーと「NEO進化：」の間に語が入るため対象外になるカード (手で確認する)
--   例: ■超無限G-NEO進化：… / ■S-NEO進化(墓地)：…
SELECT id, name, evolution, LEFT(str, 60) AS str_head
FROM cards
WHERE str LIKE '%NEO進化%'
  AND NOT (
    str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
    OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'NEO進化', ':', '%')
    OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296A0 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BEEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE296AAEFB88F USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'G-', 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), 'G-', 'NEO進化', ':', '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
      OR str LIKE CONCAT('%', CONVERT(0xE297BCEFB88E20 USING utf8), CONVERT(0x47EFBC8D USING utf8), 'NEO進化', ':', '%')
  )
  AND str LIKE CONCAT('%NEO進化', CONVERT(0xEFBC9A USING utf8), '%')
ORDER BY id;
